In [ ]:
import numpy as np # importing numpy librabry

Definig first list containing ages of 6 people.

In [ ]:
ages_list=[10,5,8,32,65,43]

There are 3 main ways to instantiate a Numpy ndarray object. One of these is to use 
 * np.array(passing the list)

In [ ]:
ages=np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [ ]:
print(ages)
print("size:\t",ages.size)
print("shape:\t",ages.shape)

[10  5  8 32 65 43]
size:	 6
shape:	 (6,)


In [ ]:
zeroArr=np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


#Multi_dim
Now Let us define a new list containing the weights of 6 peoples

In [ ]:
weight_list=[32,18,26,60,55,65]

Now, we define an ndarray containing all fo this information, and again print the size and shape of the array.

In [ ]:
people=np.array([ages_list,weight_list])
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10  5  8 32 65 43]
 [32 18 26 60 55 65]]
Size:	 12
Shape:	 (2, 6)


In [ ]:
# 2 x 6 = 1 x 12 = 4 x 3 =3 x 4 =12 x 1
people=people.reshape(12,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)


People:	 [[10]
 [ 5]
 [ 8]
 [32]
 [65]
 [43]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]
Size:	 12
Shape:	 (12, 1)


** the new shape should be be the same size as of previous.**

#EXERCISE - 1

In [ ]:
arr1=[7,9,65,33,85,99]
arr=np.array(arr1)

In [ ]:
arr

array([ 7,  9, 65, 33, 85, 99])

In [ ]:
matrix=np.array([[1,2,4],[2,3,0],[0,5,1]])

In [ ]:
matrix

array([[1, 2, 4],
       [2, 3, 0],
       [0, 5, 1]])

In [ ]:
matrix.reshape(1,9) # changed the shape of above array to 1 x 9

array([[1, 2, 4, 2, 3, 0, 0, 5, 1]])

# Array Generation

In [ ]:
five_times_table=np.arange(0,55,5) # arange will creates a range of number with user stop in it.
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
five_spaced=np.linspace(0,50,11) # it will  produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
twoArr=np.repeat(2,10) # it will repeat the object as per your specification.
twoArr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
identity_matrix=np.eye(6) # it will create identity matrix for us.
identity_matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Operations on arrays

In [ ]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


# Speed Test
If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference.

In [ ]:
fives_list = list(range(0,5001,5))
fives_list

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [ ]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [ ]:
%timeit five_times_table_lge + 5 #it is used to measure the execution time of the table

1.32 µs ± 22 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
%timeit [e + 5 for e in fives_list]

60.7 µs ± 1.95 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Boolean string operations can also be performed on ndarrays.

In [ ]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

# Transpose

In [ ]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]] 

[[10 32]
 [ 5 18]
 [ 8 26]
 [32 60]
 [65 55]
 [43 65]]


# Data Types

In [ ]:
people.dtype

dtype('int64')

What is the data type of the below ndarray?

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [ ]:
ages_with_strings.dtype

dtype('<U21')

What is the dtype of this array?

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings


array([10,  5,  8, 32, 65, 43], dtype=int32)

In [ ]:
ages_with_strings.dtype # gives the datatype of the above array

dtype('int32')

What do you think has happened here?

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)



['10' '5' '8' '32' '65' '43']


In [ ]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [ ]:
ages_with_strings.size

126

In [ ]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the .astype() method, demonstrated below.

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


Exercise:

In [ ]:
arr2=np.array([[1,2,3],[23,4,6]])

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
new_a=arr2.astype('float64') # it will the change the datatype from int to float.

In [ ]:
new_a.dtype

dtype('float64')

In [ ]:
# transpose the above matrix
transpose=arr2.transpose()

In [ ]:
transpose

array([[ 1, 23],
       [ 2,  4],
       [ 3,  6]])

In [ ]:
transpose.shape # shape of the matrix after transpose

(3, 2)

In [ ]:
transpose.size # size of the transposed matrix.

6

In [ ]:
Bool=np.array(arr2,dtype=bool) # chaning the datatype to boolean

In [ ]:
Bool

array([[ True,  True,  True],
       [ True,  True,  True]])

#Array Slicing Operations
As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array.

In [ ]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
five_times_table[0]

0

In [ ]:
five_times_table[-1]

50

In [ ]:
five_times_table[:4]

array([ 0,  5, 10, 15])

In [ ]:
five_times_table[4:]

array([20, 25, 30, 35, 40, 45, 50])

We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

In [ ]:
print(people)
people[:3, :3]

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]


array([[10,  5,  8],
       [32, 18, 26]])

#Exercise
* Create a numpy array with 50 zeros
* Create a np array of 2 repeated 20 times
* Create a numpy array from 0 to 2  in steps of 0.1

For one of the arrays generated:

* Get the first five values
* Get the last 3 values
* Get the 4th value to the 7th value

In [ ]:
zer=np.zeros(50)

In [ ]:
zer

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
repeat=np.repeat(2,20)

In [ ]:
repeat

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
import math 
arr3=np.arange(0, math.pi, 0.1)

In [ ]:
arr3

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

We can reverse an array by using .flip() or by using the :: operator.



In [ ]:
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [ ]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table


[50 45 40 35 30 25 20 15 10  5  0]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
five_times_table[0::3]

array([ 0, 15, 30, 45])

# Exercise
Take one of the arrays you defined and

#### Reverse it
#### Only keep every 4th element.
#### Get every 2nd element, starting from the last and moving backwards.

In [ ]:
array4=np.array([1,2,3,4,5,6,7])

In [ ]:
flip=np.flip(array4)

In [ ]:
flip

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
keep=array4[0::4] # will keep every 4 element 

In [ ]:
keep

array([1, 5])

In [ ]:
reverse=array4[-1::-2] # gives every second element from last

In [ ]:
reverse

array([7, 5, 3, 1])

# Stats

In [ ]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [ ]:
nums = np.arange(0, 4, 0.2555)

In [ ]:
nums

array([0.    , 0.2555, 0.511 , 0.7665, 1.022 , 1.2775, 1.533 , 1.7885,
       2.044 , 2.2995, 2.555 , 2.8105, 3.066 , 3.3215, 3.577 , 3.8325])

# Exercise
Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.


In [ ]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


# Random
With np.random, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [ ]:
flip3=np.random.choice([0,1],10)

In [ ]:
flip3

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0])

In [ ]:
a=np.random.rand(10,20,9)

In [ ]:
a

array([[[0.48751544, 0.92391623, 0.78416054, ..., 0.97487421,
         0.29190276, 0.72184117],
        [0.19781431, 0.37906802, 0.57067107, ..., 0.56917903,
         0.2797608 , 0.21024335],
        [0.3633606 , 0.51077214, 0.99499522, ..., 0.16915439,
         0.20706765, 0.15151036],
        ...,
        [0.73412824, 0.8041093 , 0.9363737 , ..., 0.69419189,
         0.08175287, 0.12067753],
        [0.9287973 , 0.45391492, 0.34016572, ..., 0.40584895,
         0.00881561, 0.9617427 ],
        [0.4418865 , 0.18461015, 0.83742335, ..., 0.73432586,
         0.23178239, 0.69344246]],

       [[0.33611088, 0.34451538, 0.19024141, ..., 0.64082984,
         0.31590007, 0.35889596],
        [0.94891899, 0.72087219, 0.95078933, ..., 0.98106137,
         0.83996223, 0.79126122],
        [0.2446065 , 0.33414009, 0.99203066, ..., 0.98461398,
         0.9374958 , 0.47332527],
        ...,
        [0.13541051, 0.12850077, 0.90641483, ..., 0.43156757,
         0.76680161, 0.74658123],
        [0.4

In [ ]:
np.random.rand(1,2,3)

array([[[0.70613021, 0.03740106, 0.2169495 ],
        [0.37783576, 0.10486674, 0.82171422]]])

We can produce 1000 datapoints of a normally distributed data set by using np.random.normal()

In [ ]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)

In [ ]:
s

array([-1.20304802e-02,  1.53459249e-01,  2.30126833e-02,  8.91338907e-02,
       -2.36050574e-05, -1.39725966e-01,  5.12002700e-02,  3.13257738e-02,
        2.84579712e-03, -1.07561348e-01, -1.62707335e-01, -6.85802140e-02,
       -3.73106119e-02, -1.18148357e-02,  5.60363122e-02,  7.67386656e-02,
       -5.86477304e-02, -2.68343001e-01,  3.64202922e-02, -3.15425836e-02,
       -6.64312817e-02,  1.53410234e-02,  1.06485481e-02, -2.05455279e-02,
        8.65151708e-02, -6.88844090e-02, -1.62984767e-01, -7.01830996e-02,
       -8.35767157e-03,  8.94029800e-02, -6.85339821e-02, -2.00246874e-01,
        5.63128696e-02,  4.23859632e-02,  1.90115163e-02, -1.71586304e-01,
       -8.69160725e-02,  7.26100198e-02,  5.31034795e-02,  4.37372406e-02,
        4.27535043e-02,  1.49680813e-01, -1.43552462e-01,  7.85265956e-02,
       -1.26400534e-01, -6.37814284e-02,  1.27438216e-01,  7.46194910e-02,
       -2.38786089e-02, -4.43771961e-02, -2.42384187e-02, -8.10829752e-03,
        7.07802014e-03, -

#Exercise
Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

In [ ]:
np.random.choice([1,2,3,4,5,6],10)

array([4, 5, 1, 1, 3, 5, 6, 4, 1, 5])

In [ ]:
toss=np.random.choice(['Head','Head','Tail'],10)

In [ ]:
toss

array(['Head', 'Head', 'Tail', 'Head', 'Head', 'Head', 'Tail', 'Head',
       'Head', 'Tail'], dtype='<U4')